---
server:
  port: 8081
---
spring:
  devtools:
    restart:
      exclude: "META-INF/resources/**,public/**"
      log-condition-evaluation-delta: true
      trigger-file: "reloadtrigger"
  mvc:
      log-request-details: false